import { resolve } from 'node:path';
import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';
import dts from 'vite-plugin-dts';

export default defineConfig({
  plugins: [
    react({
      jsxRuntime: 'automatic',
    }),
    dts({
      include: ['lib', 'shadcn'],
      exclude: ['**/*.stories.*', '**/*.test.*'],
      tsconfigPath: './tsconfig.lib.json',
      outDir: 'dist',
      insertTypesEntry: false,
      pathsToAliases: false,
      rollupTypes: false,
    }),
    tailwindcss(),
  ],
  build: {
    lib: {
      entry: {
        // Main entry point
        index: resolve(__dirname, 'lib/index.ts'),
        // Component entries
        'components/Sidebar': resolve(__dirname, 'lib/components/Sidebar/index.ts'),
        'components/Breadcrumb': resolve(__dirname, 'lib/components/Breadcrumb/index.ts'),
        'components/Alert': resolve(__dirname, 'lib/components/Alert/index.ts'),
        'components/Avatar': resolve(__dirname, 'lib/components/Avatar/index.ts'),
        'components/Badge': resolve(__dirname, 'lib/components/Badge/index.ts'),
        'components/Kbd': resolve(__dirname, 'lib/components/Kbd/index.ts'),
        'components/Button': resolve(__dirname, 'lib/components/Button/index.ts'),
        'components/ScanBarcodeButton': resolve(__dirname, 'lib/components/ScanBarcodeButton/index.ts'),
        'components/Card': resolve(__dirname, 'lib/components/Card/index.ts'),
        'components/BarChart': resolve(__dirname, 'lib/components/BarChart/index.ts'),
        'components/LineChart': resolve(__dirname, 'lib/components/LineChart/index.ts'),
        'components/AreaChart': resolve(__dirname, 'lib/components/AreaChart/index.ts'),
        'components/PieChart': resolve(__dirname, 'lib/components/PieChart/index.ts'),
        'components/RadarChart': resolve(__dirname, 'lib/components/RadarChart/index.ts'),
        'components/RadialChart': resolve(__dirname, 'lib/components/RadialChart/index.ts'),
        'components/Checkbox': resolve(__dirname, 'lib/components/Checkbox/index.ts'),
        'components/Collapsible': resolve(__dirname, 'lib/components/Collapsible/index.ts'),
        'components/CurrencyField': resolve(__dirname, 'lib/components/CurrencyField/index.ts'),
        'components/OTPField': resolve(__dirname, 'lib/components/OTPField/index.ts'),
        'components/PageContent': resolve(__dirname, 'lib/components/PageContent/index.ts'),
        'components/PageHeader': resolve(__dirname, 'lib/components/PageHeader/index.ts'),
        'components/PasswordField': resolve(__dirname, 'lib/components/PasswordField/index.ts'),
        'components/PhoneField': resolve(__dirname, 'lib/components/PhoneField/index.ts'),
        'components/Progress': resolve(__dirname, 'lib/components/Progress/index.ts'),
        'components/DangerZone': resolve(__dirname, 'lib/components/DangerZone/index.ts'),
        'components/CopyField': resolve(__dirname, 'lib/components/CopyField/index.ts'),
        'components/DetailField': resolve(__dirname, 'lib/components/DetailField/index.ts'),
        'components/FormattedDate': resolve(__dirname, 'lib/components/FormattedDate/index.ts'),
        'components/DataTable': resolve(__dirname, 'lib/components/DataTable/index.ts'),
        'components/CheckboxGroup': resolve(__dirname, 'lib/components/CheckboxGroup/index.ts'),
        'components/RadioGroup': resolve(__dirname, 'lib/components/RadioGroup/index.ts'),
        'components/Select': resolve(__dirname, 'lib/components/Select/index.ts'),
        'components/PersonSelector': resolve(__dirname, 'lib/components/PersonSelector/index.ts'),
        'components/CompanySelector': resolve(__dirname, 'lib/components/CompanySelector/index.ts'),
        'components/Sortable': resolve(__dirname, 'lib/components/Sortable/index.ts'),
        'selects/cloud-provider': resolve(__dirname, 'lib/selects/cloud-provider/index.ts'),
        'selects/business': resolve(__dirname, 'lib/selects/business/index.ts'),
        'selects/region': resolve(__dirname, 'lib/selects/region/index.ts'),
        'selects/repository': resolve(__dirname, 'lib/selects/repository/index.ts'),
        'selects/plan': resolve(__dirname, 'lib/selects/plan/index.ts'),
        'selects/billing-cycle': resolve(__dirname, 'lib/selects/billing-cycle/index.ts'),
        'selects/country': resolve(__dirname, 'lib/selects/country/index.ts'),
        'selects/currency': resolve(__dirname, 'lib/selects/currency/index.ts'),
        'selects/locale': resolve(__dirname, 'lib/selects/locale/index.ts'),
        'selects/timezone': resolve(__dirname, 'lib/selects/timezone/index.ts'),
        'selects/deployment': resolve(__dirname, 'lib/selects/deployment/index.ts'),
        'selects/feature': resolve(__dirname, 'lib/selects/feature/index.ts'),
        'selects/feature-permission': resolve(__dirname, 'lib/selects/feature-permission/index.ts'),
        'selects/icon': resolve(__dirname, 'lib/selects/icon/index.ts'),
        icons: resolve(__dirname, 'lib/icons/index.ts'),
        'types/catalog-resolver': resolve(__dirname, 'lib/types/catalog-resolver.ts'),
        'types/api-response': resolve(__dirname, 'lib/types/api-response.ts'),
        'types/table-filter': resolve(__dirname, 'lib/types/table-filter.ts'),
        'selects/app': resolve(__dirname, 'lib/selects/app/index.ts'),
        'selects/quant': resolve(__dirname, 'lib/selects/quant/index.ts'),
        'selects/app-code': resolve(__dirname, 'lib/selects/app-code/index.ts'),
        'selects/category': resolve(__dirname, 'lib/selects/category/index.ts'),
        'selects/cost-category': resolve(__dirname, 'lib/selects/cost-category/index.ts'),
        'selects/customer': resolve(__dirname, 'lib/selects/customer/index.ts'),
        'selects/inventory-item': resolve(__dirname, 'lib/selects/inventory-item/index.ts'),
        'selects/iso-country': resolve(__dirname, 'lib/selects/iso-country/index.ts'),
        'selects/lot': resolve(__dirname, 'lib/selects/lot/index.ts'),
        'selects/serial': resolve(__dirname, 'lib/selects/serial/index.ts'),
        'selects/location': resolve(__dirname, 'lib/selects/location/index.ts'),
        'selects/supplier': resolve(__dirname, 'lib/selects/supplier/index.ts'),
        'selects/supplier-item': resolve(__dirname, 'lib/selects/supplier-item/index.ts'),
        'selects/tax-group': resolve(__dirname, 'lib/selects/tax-group/index.ts'),
        'selects/tax-class': resolve(__dirname, 'lib/selects/tax-class/index.ts'),
        'selects/purchase-order': resolve(__dirname, 'lib/selects/purchase-order/index.ts'),
        'selects/purchase-order-item': resolve(__dirname, 'lib/selects/purchase-order-item/index.ts'),
        'selects/uom': resolve(__dirname, 'lib/selects/uom/index.ts'),
        'selects/user': resolve(__dirname, 'lib/selects/user/index.ts'),
        'selects/variant-option': resolve(__dirname, 'lib/selects/variant-option/index.ts'),
        'selects/modifier-group': resolve(__dirname, 'lib/selects/modifier-group/index.ts'),
        'selects/microfrontend': resolve(__dirname, 'lib/selects/microfrontend/index.ts'),
        'selects/version': resolve(__dirname, 'lib/selects/version/index.ts'),
        'selects/legal-entity': resolve(__dirname, 'lib/selects/legal-entity/index.ts'),
        'selects/site': resolve(__dirname, 'lib/selects/site/index.ts'),
        'selects/site-group': resolve(__dirname, 'lib/selects/site-group/index.ts'),
        'selects/role': resolve(__dirname, 'lib/selects/role/index.ts'),
        'components/TextField': resolve(__dirname, 'lib/components/TextField/index.ts'),
        'components/TokenInput': resolve(__dirname, 'lib/components/TokenInput/index.ts'),
        'components/SearchBar': resolve(__dirname, 'lib/components/SearchBar/index.ts'),
        'components/TextArea': resolve(__dirname, 'lib/components/TextArea/index.ts'),
        'components/Typography': resolve(__dirname, 'lib/components/Typography/index.ts'),
        'components/ThemeToggle': resolve(__dirname, 'lib/components/ThemeToggle/index.ts'),
        'components/Form': resolve(__dirname, 'lib/components/Form/index.ts'),
        'components/HierarchyGraph': resolve(__dirname, 'lib/components/HierarchyGraph/index.ts'),
        'components/DatePicker': resolve(__dirname, 'lib/components/DatePicker/index.ts'),
        'components/DateRangePicker': resolve(__dirname, 'lib/components/DateRangePicker/index.ts'),
        'components/DateTimeRangePicker': resolve(__dirname, 'lib/components/DateTimeRangePicker/index.ts'),
        'components/DateTimePicker': resolve(__dirname, 'lib/components/DateTimePicker/index.ts'),
        'components/ConfirmHost': resolve(__dirname, 'lib/components/ConfirmHost/index.ts'),
        'components/Dialog': resolve(__dirname, 'lib/components/Dialog/index.ts'),
        'components/DropdownMenu': resolve(__dirname, 'lib/components/DropdownMenu/index.ts'),
        'components/Empty': resolve(__dirname, 'lib/components/Empty/index.ts'),
        'components/ErrorBoundary': resolve(__dirname, 'lib/components/ErrorBoundary/index.ts'),
        'components/Separator': resolve(__dirname, 'lib/components/Separator/index.ts'),
        'components/Skeleton': resolve(__dirname, 'lib/components/Skeleton/index.ts'),
        'components/Sonner': resolve(__dirname, 'lib/components/Sonner/index.ts'),
        'components/Spinner': resolve(__dirname, 'lib/components/Spinner/index.ts'),
        'components/StepProgressIndicator': resolve(__dirname, 'lib/components/StepProgressIndicator/index.ts'),
        'components/PermissionGate': resolve(__dirname, 'lib/components/PermissionGate/index.ts'),
        'components/Switch': resolve(__dirname, 'lib/components/Switch/index.ts'),
        'components/Tabs': resolve(__dirname, 'lib/components/Tabs/index.ts'),
        'components/Toggle': resolve(__dirname, 'lib/components/Toggle/index.ts'),
        'components/Tooltip': resolve(__dirname, 'lib/components/Tooltip/index.ts'),
        'components/TreeView': resolve(__dirname, 'lib/components/TreeView/index.ts'),
        'components/FilePreview': resolve(__dirname, 'lib/components/FilePreview/index.ts'),
        'components/UploadFile': resolve(__dirname, 'lib/components/UploadFile/index.ts'),
        'components/ValueFilter': resolve(__dirname, 'lib/components/ValueFilter/index.ts'),
        'components/ViewTabs': resolve(__dirname, 'lib/components/ViewTabs/index.ts'),
        'components/RichTextEditor': resolve(__dirname, 'lib/components/Editor/index.tsx'),
        // shadcn entries
        'shadcn/shadcnField': resolve(__dirname, 'shadcn/shadcnField/index.ts'),
        // Hooks entries
        'hooks/index': resolve(__dirname, 'lib/hooks/index.ts'),
        // Context entries
        'context/index': resolve(__dirname, 'lib/context/index.ts'),
        // Theme entries (consolidated theme exports for Module Federation)
        'theme/index': resolve(__dirname, 'lib/theme/index.ts'),
        // Utils entries
        'utils/axios': resolve(__dirname, 'lib/utils/axios.ts'),
        'utils/motion': resolve(__dirname, 'lib/utils/motion.ts'),
        'utils/slug': resolve(__dirname, 'lib/utils/slug.ts'),
        'utils/cn': resolve(__dirname, 'lib/utils/cn.ts'),
        'utils/lodash': resolve(__dirname, 'lib/utils/lodash.ts'),
        'utils/locale': resolve(__dirname, 'lib/utils/locale.ts'),
        'utils/timezone': resolve(__dirname, 'lib/utils/timezone.ts'),
        'utils/currency': resolve(__dirname, 'lib/utils/currency.ts'),
        'utils/pluralize': resolve(__dirname, 'lib/utils/pluralize.ts'),
        'utils/zod': resolve(__dirname, 'lib/utils/zod.ts'),
        'utils/react-flow': resolve(__dirname, 'lib/utils/react-flow.ts'),
        'utils/dagre': resolve(__dirname, 'lib/utils/dagre.ts'),
        'utils/dnd-kit/core': resolve(__dirname, 'lib/utils/dnd-kit/core.ts'),
        'utils/dnd-kit/sortable': resolve(__dirname, 'lib/utils/dnd-kit/sortable.ts'),
        'utils/dnd-kit/utilities': resolve(__dirname, 'lib/utils/dnd-kit/utilities.ts'),
        'utils/hotkeys': resolve(__dirname, 'lib/utils/hotkeys.ts'),
        'utils/money': resolve(__dirname, 'lib/utils/money.ts'),
        'utils/permission-deps': resolve(__dirname, 'lib/utils/permission-deps.ts'),
        'utils/format': resolve(__dirname, 'lib/utils/format.ts'),
        'utils/decimal': resolve(__dirname, 'lib/utils/decimal.ts'),
        'utils/colors': resolve(__dirname, 'lib/utils/colors.ts'),
        'date-fns': resolve(__dirname, 'lib/date-fns.ts'),
      },
      name: 'QuantumUI',
      formats: ['es'],
      fileName: (_, entryName) => `${entryName}.js`,
    },
    rollupOptions: {
      external: (id, parentId) => {
        // Don't externalize axios when building the axios entry
        if (parentId?.includes('lib/utils/axios')) {
          return ['react', 'react-dom', 'react/jsx-runtime', 'react-router-dom'].includes(id);
        }
        // zod and @hookform/resolvers are intentionally NOT in externals — they're only
        // imported from lib/utils/zod, so Rollup bundles them into the zod chunk only.
        // Apps must consume them via @vritti/quantum-ui/zod.
        return [
          'react',
          'react-dom',
          'react/jsx-runtime',
          'axios',
          'react-router-dom',
          '@tanstack/react-query',
        ].includes(id);
      },
      output: {
        assetFileNames: 'assets/[name][extname]',
        entryFileNames: '[name].js',
        chunkFileNames: '[name].js',
      },
    },
    cssCodeSplit: false,
    sourcemap: true,
    target: 'esnext',
    minify: false,
  },
});
